import { useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { PageHeader, Btn } from '../../components/shared'
import { FormField, Input } from '../../components/forms'
import { EmitirDteModal } from '../../components/facturacion/DteModals'
import { DteItemsEditor } from '../../components/facturacion/DteItemsEditor'
import { useProveedores } from '../../api/proveedores'
import { toast } from '../../store/notif'

function ProveedorAutocomplete({ onSelect }) {
  const [query, setQuery] = useState(''); const [debounced, setDebounced] = useState(''); const [open, setOpen] = useState(false); const boxRef = useRef(null)
  useEffect(() => { const timeout = setTimeout(() => setDebounced(query.trim()), 300); return () => clearTimeout(timeout) }, [query])
  useEffect(() => { const close = event => { if (boxRef.current && !boxRef.current.contains(event.target)) setOpen(false) }; document.addEventListener('mousedown', close); return () => document.removeEventListener('mousedown', close) }, [])
  const { data, isFetching } = useProveedores(debounced.length >= 2 ? { search: debounced } : {}); const items = debounced.length >= 2 ? data?.items || [] : []
  return <div ref={boxRef} style={{ position: 'relative', marginBottom: 16 }}><FormField label="Buscar proveedor existente (rellena el receptor)"><Input value={query} onChange={value => { setQuery(value); setOpen(true) }} placeholder="RUT o nombre..." /></FormField>{open && debounced.length >= 2 && <div style={dropdownStyle}>{isFetching && <div style={resultText}>Buscando...</div>}{!isFetching && !items.length && <div style={resultText}>Sin resultados</div>}{items.map(item => <button key={item.id} type="button" onClick={() => { onSelect(item); setQuery(''); setOpen(false) }} style={resultButton}><b>{item.razonSocial || item.nombre}</b><small>{item.rut}</small></button>)}</div>}</div>
}
const dropdownStyle = { position: 'absolute', top: '100%', left: 0, right: 0, zIndex: 20, background: '#fff', border: '1px solid var(--border)', borderRadius: 8, boxShadow: '0 8px 24px oklch(0 0 0 / .12)', maxHeight: 240, overflowY: 'auto' }
const resultButton = { display: 'grid', width: '100%', gap: 2, padding: '8px 10px', textAlign: 'left', background: 'none', border: 'none', borderBottom: '1px solid var(--border)', cursor: 'pointer', fontSize: 13 }
const resultText = { padding: 10, color: 'var(--text-3)', fontSize: 12 }

export default function EmitirFacturaCompraPage() {
  const navigate = useNavigate(); const [proveedor, setProveedor] = useState({ rut: '', razonSocial: '', giro: '', direccion: '', comuna: '', ciudad: '' }); const [items, setItems] = useState([]); const [showModal, setShowModal] = useState(false)
  const setField = (field, value) => setProveedor(current => ({ ...current, [field]: value }))
  const selectProveedor = item => setProveedor({ rut: item.rut || '', razonSocial: item.razonSocial || item.nombre || '', giro: item.giro || '', direccion: item.direccion || '', comuna: item.comuna || '', ciudad: item.ciudad || '' })
  const itemsValidos = items.filter(item => item.nombre.trim() && Number(item.cantidad) > 0)
  const compraSintetica = { id: null, clienteId: null, cliente: proveedor, items: itemsValidos.map((item, index) => ({ id: `compra-${index}`, nombre: item.nombre.trim(), descripcion: item.descripcion || null, cantidad: Number(item.cantidad), precioUnitario: Number(item.precioUnitario), exento: item.exento })) }
  return <main className="page page-wide"><PageHeader title="Emitir factura de compra" subtitle="DTE 46 a un proveedor, sin venta asociada" breadcrumb={['Inicio', 'Facturación', 'Factura de compra']} /><div style={{ background: '#fff', border: '1px solid var(--border)', borderRadius: 8, padding: 20, maxWidth: 1120 }}><div style={{ padding: '10px 12px', marginBottom: 16, borderRadius: 8, background: 'var(--bg)', color: 'var(--text-2)', fontSize: 13 }}>El proveedor es el receptor tributario de esta Factura de Compra Electrónica.</div><h3 style={{ margin: '0 0 12px', fontSize: 15 }}>Proveedor</h3><ProveedorAutocomplete onSelect={selectProveedor} /><div style={grid2}><FormField label="RUT"><Input value={proveedor.rut} onChange={value => setField('rut', value)} /></FormField><FormField label="Razón social / Nombre"><Input value={proveedor.razonSocial} onChange={value => setField('razonSocial', value)} /></FormField></div><div style={grid2}><FormField label="Giro"><Input value={proveedor.giro} onChange={value => setField('giro', value)} /></FormField><FormField label="Dirección"><Input value={proveedor.direccion} onChange={value => setField('direccion', value)} /></FormField></div><div style={{ ...grid2, marginBottom: 20 }}><FormField label="Comuna"><Input value={proveedor.comuna} onChange={value => setField('comuna', value)} /></FormField><FormField label="Ciudad"><Input value={proveedor.ciudad} onChange={value => setField('ciudad', value)} /></FormField></div><h3 style={{ margin: '0 0 12px', fontSize: 15 }}>Ítems a comprar</h3><DteItemsEditor items={items} onChange={setItems} /><div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8, marginTop: 22 }}><Btn variant="ghost" onClick={() => navigate('/facturacion/documentos')}>Cancelar</Btn><Btn variant="primary" disabled={!itemsValidos.length || !proveedor.rut || !proveedor.razonSocial} onClick={() => setShowModal(true)}>Continuar a emisión</Btn></div></div>{showModal && <EmitirDteModal venta={compraSintetica} tipoDte={46} onClose={() => setShowModal(false)} onSuccess={({ emitido, documento }) => { setShowModal(false); toast.success(`Factura de compra emitida${emitido?.folio || documento?.folio ? `: folio ${emitido?.folio || documento?.folio}` : ''}`); navigate('/facturacion/documentos') }} />}</main>
}
const grid2 = { display: 'grid', gridTemplateColumns: '1fr 2fr', gap: 12, marginBottom: 12 }
